# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20170709_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comments_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
